// Dental condition definitions — color, labels, scope, overlays
export const CONDITIONS = [
  // ── Restorative ───────────────────────────────────────────────────────────
  {
    id: 'healthy',
    label: 'Healthy',
    labelAr: 'سليم',
    color: '#FFFFFF',
    stroke: '#BDBDBD',
    toothLevel: false,
    group: 'restorative',
  },
  {
    id: 'caries',
    label: 'Caries',
    labelAr: 'تسوس',
    color: '#EF5350',
    stroke: '#C62828',
    toothLevel: false,
    group: 'restorative',
  },
  {
    id: 'filling_composite',
    label: 'Composite',
    labelAr: 'حشو كمبوزيت',
    color: '#42A5F5',
    stroke: '#1565C0',
    toothLevel: false,
    group: 'restorative',
  },
  {
    id: 'filling_amalgam',
    label: 'Amalgam',
    labelAr: 'حشو أملغم',
    color: '#78909C',
    stroke: '#37474F',
    toothLevel: false,
    group: 'restorative',
  },
  {
    id: 'filling_gic',
    label: 'GIC',
    labelAr: 'حشو GIC',
    color: '#A5D6A7',
    stroke: '#2E7D32',
    toothLevel: false,
    group: 'restorative',
  },
  {
    id: 'sealant',
    label: 'Sealant',
    labelAr: 'حاجب تشققات',
    color: '#B2DFDB',
    stroke: '#00695C',
    toothLevel: false,
    group: 'restorative',
  },
  {
    id: 'fracture',
    label: 'Fracture',
    labelAr: 'كسر',
    color: '#FFCDD2',
    stroke: '#B71C1C',
    toothLevel: false,
    group: 'restorative',
    overlay: 'fracture',
  },
  // ── Prosthetic ────────────────────────────────────────────────────────────
  {
    id: 'crown_ceramic',
    label: 'Ceramic Crown',
    labelAr: 'تاج خزفي',
    color: '#FFF9C4',
    stroke: '#F9A825',
    toothLevel: true,
    group: 'prosthetic',
  },
  {
    id: 'crown_metal',
    label: 'Metal Crown',
    labelAr: 'تاج معدني',
    color: '#CFD8DC',
    stroke: '#455A64',
    toothLevel: true,
    group: 'prosthetic',
  },
  {
    id: 'crown_pfm',
    label: 'PFM Crown',
    labelAr: 'تاج خزف معدني',
    color: '#FFD54F',
    stroke: '#F57F17',
    toothLevel: true,
    group: 'prosthetic',
  },
  {
    id: 'crown_zirconia',
    label: 'Zirconia',
    labelAr: 'زيركونيا',
    color: '#E1F5FE',
    stroke: '#0288D1',
    toothLevel: true,
    group: 'prosthetic',
  },
  {
    id: 'veneer',
    label: 'Veneer',
    labelAr: 'قشرة',
    color: '#F3E5F5',
    stroke: '#7B1FA2',
    toothLevel: true,
    group: 'prosthetic',
  },
  {
    id: 'bridge_abutment',
    label: 'Bridge Abutment',
    labelAr: 'دعامة جسر',
    color: '#FFF3E0',
    stroke: '#F57C00',
    toothLevel: true,
    group: 'prosthetic',
    overlay: 'bridge',
  },
  {
    id: 'bridge_pontic',
    label: 'Bridge Pontic',
    labelAr: 'حامل جسر',
    color: '#FFF3E0',
    stroke: '#F57C00',
    toothLevel: true,
    group: 'prosthetic',
    overlay: 'bridge',
  },
  {
    id: 'implant',
    label: 'Implant',
    labelAr: 'زراعة',
    color: '#E8F5E9',
    stroke: '#2E7D32',
    toothLevel: true,
    group: 'prosthetic',
    overlay: 'implant',
  },
  // ── Endodontic ────────────────────────────────────────────────────────────
  {
    id: 'root_canal',
    label: 'Root Canal',
    labelAr: 'علاج عصب',
    color: '#FFE0B2',
    stroke: '#E65100',
    toothLevel: true,
    group: 'endodontic',
    overlay: 'root_canal',
  },
  // ── Other ─────────────────────────────────────────────────────────────────
  {
    id: 'missing',
    label: 'Missing',
    labelAr: 'مفقود',
    color: '#F5F5F5',
    stroke: '#9E9E9E',
    toothLevel: true,
    group: 'other',
    overlay: 'X',
  },
  {
    id: 'unerupted',
    label: 'Unerupted',
    labelAr: 'لم يبزغ',
    color: '#E8EAF6',
    stroke: '#3949AB',
    toothLevel: true,
    group: 'other',
  },
  {
    id: 'impacted',
    label: 'Impacted',
    labelAr: 'مطمور',
    color: '#FCE4EC',
    stroke: '#C62828',
    toothLevel: true,
    group: 'other',
  },
  {
    id: 'extraction_planned',
    label: 'Extraction',
    labelAr: 'مقرر خلعه',
    color: '#FFEBEE',
    stroke: '#C62828',
    toothLevel: true,
    group: 'other',
    overlay: 'X_planned',
  },
  {
    id: 'periodontal',
    label: 'Periodontal',
    labelAr: 'أمراض لثة',
    color: '#FFF3E0',
    stroke: '#E65100',
    toothLevel: false,
    group: 'other',
  },
  {
    id: 'orthodontic',
    label: 'Orthodontic',
    labelAr: 'تقويم',
    color: '#E8F5E9',
    stroke: '#1B5E20',
    toothLevel: true,
    group: 'other',
  },
  {
    id: 'watch',
    label: 'Watch',
    labelAr: 'مراقبة',
    color: '#FFFDE7',
    stroke: '#F9A825',
    toothLevel: false,
    group: 'other',
  },
];

export const CONDITION_GROUPS = [
  { id: 'restorative', label: 'Restorative', labelAr: 'ترميمي' },
  { id: 'prosthetic', label: 'Prosthetic', labelAr: 'تعويضي' },
  { id: 'endodontic', label: 'Endodontic', labelAr: 'قناة جذر' },
  { id: 'other', label: 'Other', labelAr: 'أخرى' },
];

export const getCondition = (id) => CONDITIONS.find((c) => c.id === id) || null;

export const getConditionColor = (id) => getCondition(id)?.color || '#FFFFFF';
export const getConditionStroke = (id) => getCondition(id)?.stroke || '#BDBDBD';
export const getConditionLabel = (id, lang = 'en') =>
  lang === 'ar' ? (getCondition(id)?.labelAr || id) : (getCondition(id)?.label || id);
