import axios from 'axios';

import { HOST_API } from 'src/config-global';
// import { idText } from 'typescript';


// https://axios-http.com/docs/instance
// ----------------------------------------------------------------------

const axiosInstance = axios.create({ baseURL: HOST_API });

axiosInstance.interceptors.response.use(
  (res) => res,
  (error) => Promise.reject((error.response && error.response.data) || 'Something went wrong')
);

export default axiosInstance;

// ----------------------------------------------------------------------

export const fetcher = async (args) => {
  const [url, config] = Array.isArray(args) ? args : [args];

  const res = await axiosInstance.get(url, { ...config });

  return res.data;
};

// ----------------------------------------------------------------------

export const endpoints = {

  allTables: '/tables',
  tables: {
    countries: `/api/countries`,
    country: (id) => `/api/countries/${id}`,
    cities: '/api/cities',
    city: (id) => `/api/cities/${id}`,
    surgeries: '/api/surgeries',
    surgery: (id) => `/api/surgeries/${id}`,
    diseases: '/api/diseases',
    disease: (id) => `/api/diseases/${id}`,
    symptoms: '/api/symptoms',
    symptom: (id) => `/api/symptoms/${id}`,
    categories: '/api/medcategories',
    category: (id) => `/api/medcategories/${id}`,
    currencies: '/api/currency',
    currency: (id) => `/api/currency/${id}`,
    medfamilies: '/api/drugfamilies',
    medfamily: (id) => `/api/drugfamilies/${id}`,
    medicines: '/api/medicines',
    medicine: (id) => `/api/medicines/${id}`,
    diets: '/api/diets',
    diet: (id) => `/api/diets/${id}`,
    analyses: '/api/analysis',
    analysis: (id) => `/api/analysis/${id}`,
    insuranceCos: '/api/insurance/companies',
    insuranceCo: (id) => `/api/insurance/companies/${id}`,
    insuranceTypes: '/api/insurance/types',
    insuranceType: (id) => `/api/insurance/types/${id}`,
    unitservices: '/api/unitservice',
    unitservice: (id) => `/api/unitservice/${id}`,
    departments: '/api/departments',
    unitServiceDepartments: (id)=> `/api/departments/unitservice/${id}`,
    department: (id) => `/api/departments/${id}`,
    specialities: '/api/specialities',
    speciality: (id) => `/api/specialities/${id}`,
    subspecialties: '/api/subspecialities',
    subspeciality: (id) => `/api/subspecialities/${id}`,
    appointmenttypes: '/api/appointments/types',
    appointmenttype: (id) => `/api/appointments/types/${id}`,
    appointmentconfigs: '/api/appointments/config',
    employeeAppointmentconfig: (emid) => `/api/appointments/config/employee/${emid}`,
    usEmployeeAppointmentconfig: (id,emid) => `/api/appointments/config/unitservice/${id}/employee/${emid}`,
    usEmployeeAppointments: (id,emid) => `/api/appointments/unitservice/${id}/employee/${emid}`,
    departmentEmployeeAppointmentconfig: (id,emid) => `/api/appointments/config/department/${id}/employee/${emid}`,
    appointmentconfig: (id) => `/api/appointments/config/${id}`,
    usappointmentconfig: (id) => `/api/appointments/config/unitservice/${id}`,
    usappointmentconfigcount: (id) => `/api/appointments/config//unitservice${id}/count`,
    departmentappointmentconfig: (id) => `/api/appointments/config/department/${id}`,
    departmentappointmentconfigcount: (id) => `/api/appointments/config/department/${id}/count`,
    freesubscriptions: '/api/freesubscription',
    freesubscription: (id) => `/api/freesubscription/${id}`,
    unitservicetypes: '/api/ustypes',
    unitservicetype: (id) => `/api/ustypes/${id}`,
    taxes: '/api/taxes',
    tax: (id) => `/api/taxes/${id}`,
    activities: '/api/activities',
    usActivities: (id)=>`/api/activities/unitservice/${id}`,
    usActivitiesCount: (id)=>`/api/activities/unitservice${id}/count`,
    departmentActivities: (id)=>`/api/activities/department/${id}`,
    departmentActivitiesCount: (id)=>`/api/activities/department/${id}/count`,
    activity: (id) => `/api/activities/${id}`,
    employeetypes: '/api/employeetypes',
    usEmployeetypes: (id) => `/api/employeetypes/unitservice/${id}`,
    employeetype: (id) => `/api/employeetypes/${id}`,
    employees: '/api/employees',
    employee: (id) => `/api/employees/${id}`,
    employeeEngagements:`/api/employees/engagement`,
    employeeEngagement: (id) => `/api/employees/engagement/${id}`,
    usEmployees: (id) => `/api/employees/engagement/unitservice/${id}`,
    usEmployeesCount: (id) => `/api/employees/engagement/unitservice/${id}/count`,
    departmentEmployees: (id) => `/api/employees/engagement/department/${id}`,
    departmentEmployeesCount: (id) => `/api/employees/engagement/department/${id}/count`,
    paymentmethods: '/api/paymentmethod',
    paymentmethod: (id) => `/api/paymentmethod/${id}`,
    stakeholdertypes: '/api/stakeholdertype',
    stakeholdertype: (id) => `/api/stakeholdertype/${id}`,
    stakeholders: '/api/stakeholder',
    stakeholder: (id) => `/api/stakeholder/${id}`,
    workshifts: '/api/wshifts',
    usWorkshifts: (id) => `/api/wshifts/unitservice/${id}`,
    workshift: (id) => `/api/wshifts/${id}`,
    workgroups: '/api/wgroups',
    departmentWorkgroups: (id) => `/api/wgroups/department/${id}`,
    usWorkgroups: (id) => `/api/wgroups/unitservice/${id}`,
    employeeWorkgroups: (id) => `/api/wgroups/employee/${id}`,
    departmentemployeeWorkgroups: (id,emid) => `/api/wgroups/department/${id}/employee/${emid}`,
    usemployeeWorkgroups: (id,emid) => `/api/wgroups/unitservice/${id}/employee/${emid}`,
    workgroup: (id) => `/api/wgroups/${id}`,
    servicetypes: '/api/servicetypes',
    servicetype: (id) => `/api/servicetypes/${id}`,
    usServiceTypes: (id) => `/api/servicetypes/unitservice/${id}`,
    measurmenttypes: '/api/measurementtypes',
    measurmenttype: (id) => `/api/measurementtypes/${id}`,
    hospitals: '/api/hospital',
    hospital: (id) => `/api/hospital/${id}`,
    deductions: '/api/deductionconfig',
    deduction: (id) => `/api/deductionconfig/${id}`,
    rooms: '/api/rooms',
    room: (id) => `/api/rooms/${id}`,
    usRooms: (id) => `/api/rooms/unitservice/${id}`,
    usRoomsCount: (id) => `/api/rooms/unitservice/${id}/count`,
    departmentRooms: (id) => `/api/rooms/department/${id}`,
    departmentRoomsCount: (id) => `/api/rooms/department/${id}/count`,
    patients: '/api/patient',
    findPatients: '/api/patient/find',
    patient: (id) => `/api/patient/${id}`,
    oldpatient: () => `/api/oldpatientsdata/details`,
    unitServiceLicenseMovement: (id) => `/api/licensemovements/unitservice/${id}`,
    unitServiceLicenseMovements: `/api/licensemovements/unitservice`,
    stakeholderLicenseMovement: (id) => `/api/licensemovements/stakeholder/${id}`,
    stakeholderLicenseMovements: `/api/licensemovements/stakeholder`,
    licenseMovement: (id) => `/api/licensemovements/${id}`,
    licenseMovements: `/api/licensemovements`,
    subscriptions: '/api/subscription',
    subscription: (id) => `/api/subscription/${id}`,
    feedbacks: '/api/feedback',
    doctornafeedbacks: '/api/feedback/doctorna',
    USsfeedbacks: '/api/feedback/unitservices',
    stakeholdersfeedbacks: '/api/feedback/stakeholders',
    USfeedbacks: (id) => `/api/feedback/unitservice/${id}`,
    USfeedbacksCount: (id) => `/api/feedback/unitservice/${id}/count`,
    departmentfeedbacks: (id) => `/api/feedback/department/${id}`,
    employeefeedbacks: (id) => `/api/feedback/employee/${id}`,
    usemployeefeedbacks: (id,emid) => `/api/feedback/unitservice/${id}/employee/${emid}`,
    departmentemployeefeedbacks: (id,emid) => `/api/feedback/department/${id}/employee/${emid}`,
    departmentfeedbacksCount: (id) => `/api/feedback/department/${id}/count`,
    patientfeedbacks: (id) => `/api/feedback/patient/${id}`,
    stakeholderFeedbacks: (id) => `/api/feedback/stakeholder/${id}`,
    feedback: (id) => `/api/feedback/${id}`,
    appointments: '/api/appointments',
    availableAppointments: '/api/appointments/available',
    appointment: (id) => `/api/appointments/${id}`,
    createPatientAndBookAppoint: (id) => `/api/appointments/${id}/newpatient`,
    usAppointments: (id) => `/api/appointments/unitservice/${id}`,
    usAppointmentsCount: (id) => `/api/appointments/unitservice/${id}/count`,
    departmentAppointments: (id) => `/api/appointments/department/${id}`,
    departmentAppointmentsCount: (id) => `/api/appointments/department/${id}/count`,
    employeeAppointments: (id) => `/api/appointments/employee/${id}`,
    patientAppointments: (id) => `/api/appointments/patient/${id}`,
    economecMovements: '/api/economicmovements',
    economicMovement: (id) => `/api/economicmovements/${id}`,
    patienteconomicMovements: (id) => `/api/economicmovements/patient/${id}`,
    stakeholdereconomicMovements: (id) => `/api/economicmovements/stakeholder/${id}`,
    usEconomicMovements: (id) => `/api/economicmovements/unitservice/${id}`,
    usEconomicMovementsCount: (id) => `/api/economicmovements/unitservice/${id}/count`,
    departmentEconomicMovements: (id) => `/api/economicmovements/department/${id}`,
    departmentEconomicMovementsCount: (id) => `/api/economicmovements/department/${id}/count`,
    incomePaymentControl: '/api/incomepayment',
    incomePayment: (id) => `/api/incomepayment/${id}`,
    offers: '/api/suppliersoffers',
    offer: (id) => `/api/suppliersoffers/${id}`,
    stakeholderOffers: (id) => `/api/suppliersoffers/stakeholder/${id}`,
    patientIncomePaymentControl: (id) => `/api/incomepayment/patient/${id}`,
    departmentIncomePaymentControl: (id) => `/api/incomepayment/department/${id}`,
    stakeholderIncomePaymentControl: (id) => `/api/incomepayment/stakeholder/${id}`,
    systemErrors: '/api/systemerrors',
    systemError: (id) => `/api/systemerrors/${id}`,
    user: `/api/patient/`,
  },
  chat: '/api/chat',
  kanban: '/api/kanban',
  calendar: '/api/calendar',
  auth: {
    me: '/api/auth/me',
    login: '/api/auth/login',
    activate: (token)=>`/api/auth/activate/${token}`,
    register: '/api/auth/signup',
    forgotpassword: '/api/auth/forgotpassword',
    resetpassword: '/api/auth/resetpassword',
    updatepassword: '/api/auth/updateCurrentPassowrd',
  },
  mail: {
    list: '/api/mail/list',
    details: '/api/mail/details',
    labels: '/api/mail/labels',
  },
  post: {
    list: '/api/post/list',
    details: '/api/post/details',
    latest: '/api/post/latest',
    search: '/api/post/search',
  },
  product: {
    list: '/api/product/list',
    details: '/api/product/details',
    search: '/api/product/search',
  },

  // patients:{
  //   onepatients: '/api/patient/656af6ccac70bc1aa4120dad',
  // },
  offers: {
    getoffers: '/api/suppliersoffers',
    getoffer: (id) => `/api/suppliersoffers/${id}`,
  },
  stakeholder: {
    getstakeholder: '/api/stakeholder',
  },
  posts: {
    getAll: '/api/post',
  },
  countries: {
    getAllcountries: '/api/countries/',
  },
  payment: {
    getAllpaymentmethods: '/api/paymentmethods',
  },
};
